#!/bin/bash

# See the documentation at https://docs.docker.com/docker-hub/builds/advanced/
echo "------ HOOK START - BUILD -------"
printenv

docker image build --no-cache --tag $IMAGE_NAME --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg GIT_COMMIT=$SOURCE_COMMIT .

echo "------ HOOK END - BUILD -------"
